### PR TITLE
[FIX] component trigger needs 'on-' prefix

### PR DESCRIPTION
**Pull request by NL66278**
Fixes for some small things I encountered.

### CODE REVIEW

**Comment by PhilDL** [comment]
Hi @NL66278, thank you for your contribution.

I'm okay with the commit 25f501b60f509251323dd8a1e417635b4dac85b5 that remove the deletingArticle / deltingArticle.

But the other commit breaks the code, you can see it in the [autobuilt Netflify preview of your PR](https://deploy-preview-27--owl-realworld.netlify.app/). 
If you click (assumed you are logged-in) the like button on any article, it doesn't change the icon.


The event name that you fire can be written in any way you want but, on the XML you have to prefix it by `t-on-XXX`.

If you change the name of the event to `on-update-favorited`, 
you would have to change the XML template to `t-on-on-update-favorited`

**Review by PhilDL — CHANGES_REQUESTED** [review]
Please remove the change of triggered event name.

**Comment by NL66278** [comment]
I removed the change of the triggered event name. I must note that I do not get this part to work. Somewhere I am missing how the triggered event is getting to the event handler. Might be due to the fact that I try to do everything in pure ES6.

**Comment by PhilDL** [comment]
Thank you, LGTM.

I'm interested in your problem if you have any repo to share with me where the events aren't triggered i can take a look and try.

For this specific repository, you may have noticed sometimes the server-side is not responding or is having CORS issues. This is due to the fact that the public API https://conduit.productionready.io/api is having a bit of a rework to avoid all the SPAM and NSFW Content.

If you are facing an issue in your dev environment you can replace the URL with that temporary API URL:

https://realworld-temp-api.herokuapp.com/api

**Review by PhilDL — APPROVED** [review]

**Comment by NL66278** [comment]
Hi @PhilDL thanks for merging. I noted that the offical backend was not responding very well. Caused me a lot of headscratching. When I tried the Heroku server was not up at all. I finally installed the FastApi backend - https://github.com/nsidnev/fastapi-realworld-example-app - on my local machine. Not to well documented but got it up and running in a fairly short amount of time.

**Comment by NL66278** [comment]
@PhilDL I figured out the problem with the event handlers. Maybe other people could use a little bit more explanation, or maybe I am just not that smart. I think the Odoo OWL dcumentation does not explain it very well. Anyhow I now understand the `"updated-favorited"` event bubbles up unti it gets to the `ArticleMeta` element in `articlePage.js`, which then invokes the `onUpdateFollowing` in the same module.

**Comment by PhilDL** [comment]
@NL66278 Thank you for your feedback, I understand it's not natural that the event bubble indefinitely up the Component tree. It basically "jumped" one Component level in this example.

I explain it in [part 4 of the article](https://codingdodo.com/realworld-app-with-owl-odoo-web-library-part-4/) but maybe it's not clear, I will try to re-work this section to explain better.

**Pull request merged**
